package com.hilmsf.cms.config;


import com.hilmsf.cms.model.entity.Tag;
import com.hilmsf.cms.model.entity.Profile;
import com.hilmsf.cms.repository.TagRepository;
import com.hilmsf.cms.repository.ProfileRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
public class DataSeeder {

    private final TagRepository tagRepository;
    private final ProfileRepository profileRepository;

    public DataSeeder(TagRepository tagRepository, ProfileRepository profileRepository) {
        this.tagRepository = tagRepository;
        this.profileRepository = profileRepository;
    }

    @PostConstruct
    @Transactional
    public void seedData() {
        seedProfile();
        seedTags();
    }

    private void seedProfile() {
        if (profileRepository.count() > 0) {
            return;
        }

        Profile profile = new Profile();
        profile.setName("Hilmy");
        profile.setEmail("hilmy@example.com");
        profile.setDescription("Mobile and fullstack engineer");
        profile.setMotto("Build fast, learn fast");
        profile.setProfileImageUrl("https://example.com/profile.jpg");
        profile.setLinkedinUrl("https://linkedin.com/in/hilmysf");
        profile.setResumeUrl("https://example.com/resume.pdf");
        profile.setGithubUrl("https://github.com/hilmysf");

        profileRepository.save(profile);
        System.out.println("✅ Profile seeded");
    }

    private void seedTags() {
        if (tagRepository.count() > 0) {
            return;
        }

        tagRepository.save(createTag("Available In Playstore"));
        tagRepository.save(createTag("Private"));
        tagRepository.save(createTag("Public"));
        tagRepository.save(createTag("Production Ready"));

        System.out.println("✅ Tags seeded");
    }

    private Tag createTag(String title) {
        Tag tag = new Tag();
        tag.setTitle(title);
        // titleSlug auto-generated by @PrePersist
        return tag;
    }
}